project:
  type: website

website:
  title: "Kenneth Low"

  navbar:
    left:
      - href: projects/index.qmd
        text: Projects
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume

    right:
      - icon: github
        href: https://github.com/kaxlow

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true